AWSTemplateFormatVersion: "2010-09-09"
Description: "CodePipeline for deploying the series service"

Parameters:
  ProjectPrefixLower:
    Type: String
    Description: "lowercase prefix for the project"
  EnvType:
    Type: String
    Description: "Environment type"
    AllowedValues:
      - dev
      - prod
      - test
  GitHubRepoOwner:
    Type: String
    Description: "GitHub repository owner"
  GitHubRepoName:
    Type: String
    Description: "GitHub repository name"
  GitHubBranch:
    Type: String
    Description: "GitHub branch"
  
Resources:
  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-CodePipelineServiceRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - s3:*
                Resource: "*"
                Effect: Allow
              - Action:
                  - sns:*
                Resource: "*"
                Effect: Allow
              - Action:
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:UpdateStack
                  - cloudformation:CreateChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:SetStackPolicy
                  - cloudformation:ValidateTemplate
                  - iam:PassRole
                Resource: "*"
                Effect: Allow
              - Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuildBatches
                  - codebuild:StartBuildBatch
                Resource: "*"
                Effect: Allow
              - Action:
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeSubnets
                  - ec2:DescribeVpcs
                Effect: "Allow"
                Resource: "*"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codepipeline.amazonaws.com"
            Action:
              - "sts:AssumeRole"

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${AWS::StackName}-Pipeline
      RoleArn: !GetAtt PipelineRole.Arn
      ArtifactStore: 
        Type: S3
        Location: 
          Fn::ImportValue: !Sub "${ProjectPrefixLower}-${EnvType}-artifacts-bucket"
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: !Ref GitHubRepoOwner
                Repo: !Ref GitHubRepoName
                Branch: !Ref GitHubBranch
                OAuthToken: "{{resolve:secretsmanager:github/park-bitset/accesstoken:SecretString:GITHUB_ACCESS_TOKEN}}"
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ProjectName: !Ref UploadLambdaCodeBuildProject
              RunOrder: 1

  UploadLambdaCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-UploadLambdaCodeBuildProject
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        Type: LINUX_CONTAINER
      Source:
        Type: CODEPIPELINE
        BuildSpec: code_series/codebuild_buildspecs/buildspec.yml
      TimeoutInMinutes: 10

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-CodeBuild-ServiceRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: LambdaPolicy
                Effect: Allow
                Action:
                  - lambda:*
                Resource:
                  - "*"
              - Sid: CloudWatchLogsPolicy
                Effect: Allow
                Action:
                  - logs:*
                Resource:
                  - "*"
              - Sid: S3Policy
                Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:DeleteBucket
                  - s3:PutBucket
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:GetObjectVersion
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                  - s3:PutObject
                  - s3:ListBucket
                  - s3:SetBucketEncryption
                  - s3:GetEncryptionConfiguration
                  - s3:PutEncryptionConfiguration
                  - s3:PutBucketPolicy
                  - s3:PutLifecycleConfiguration
                  - s3:PutBucketNotification
                Resource:
                  - "*"
              - Sid: SSMParameter
                Action:
                  - ssm:AddTagsToResource
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:DeleteParameter
                  - ssm:DeleteParameters
                  - ssm:PutParameter
                  - ssm:RemoveTagsFromResource
                  - ssm:GetParametersByPath
                Effect: Allow
                Resource:
                  - "*"
              - Sid: SecretsManager
                Action:
                  - secretsmanager:ListSecrets
                  - secretsmanager:DescribeSecret
                  - secretsmanager:GetSecretValue
                Effect: Allow
                Resource:
                  - "*"
              - Action:
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStacks
                  - cloudformation:UpdateStack
                  - cloudformation:CreateChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:SetStackPolicy
                  - cloudformation:ValidateTemplate
                  - cloudformation:GetTemplateSummary
                  - cloudformation:ListStackResources
                Resource: "*"
                Effect: Allow
              - Action:
                  - cloudwatch:PutMetricAlarm
                  - cloudwatch:DeleteAlarms
                Resource: "*"
                Effect: Allow
              - Action:
                  - dynamodb:CreateTable
                  - dynamodb:DescribeTable
                  - dynamodb:DeleteTable
                  - dynamodb:UpdateTable
                  - dynamodb:UpdateTimeToLive
                  - dynamodb:DescribeTimeToLive
                Resource: "*"
                Effect: Allow
              - Action:
                  - iot:*
                Resource: "*"
                Effect: Allow
              - Action:
                  - iam:AddRoleToInstanceProfile
                  - iam:AttachRolePolicy
                  - iam:CreateRole
                  - iam:CreateInstanceProfile
                  - iam:CreateServiceLinkedRole
                  - iam:DeleteInstanceProfile
                  - iam:DeleteRole
                  - iam:DeleteRolePolicy
                  - iam:DetachRolePolicy
                  - iam:GetRole
                  - iam:GetRolePolicy
                  - iam:PassRole
                  - iam:PutRolePolicy
                  - iam:RemoveRoleFromInstanceProfile
                  - iam:UntagUser
                  - iam:UntagRole
                  - iam:UpdateAssumeRolePolicy
                  - iam:TagRole
                  - iam:TagUser
                Resource: "*"
                Effect: Allow
              - Action:
                  - apigateway:*
                Resource: "*"
                Effect: Allow
              - Action:
                  - cognito-idp:AdminInitiateAuth
                  - cognito-idp:CreateResourceServer
                  - cognito-idp:CreateUserPool
                  - cognito-idp:CreateUserPoolClient
                  - cognito-idp:CreateUserPoolDomain
                  - cognito-idp:DeleteResourceServer
                  - cognito-idp:DeleteUserPool
                  - cognito-idp:DeleteUserPoolClient
                  - cognito-idp:DeleteUserPoolDomain
                  - cognito-idp:DescribeUserPool
                  - cognito-idp:DescribeUserPoolClient
                  - cognito-idp:DescribeUserPoolDomain
                  - cognito-idp:ListUserPoolClients
                  - cognito-idp:ListUserPools
                  - cognito-idp:UpdateUserPool
                  - cognito-idp:UpdateUserPoolClient
                Resource: "*"
                Effect: Allow
              - Action:
                  - ec2:CreateNetworkInterface
                  - ec2:CreateNetworkInterfacePermission
                  - ec2:DescribeDhcpOptions
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeSubnets
                  - ec2:DescribeVpcs
                Resource: "*"
                Effect: Allow
              - Action:
                  - events:DeleteRule
                  - events:DescribeRule
                  - events:PutRule
                  - events:PutTargets
                  - events:RemoveTargets
                Resource: "*"
                Effect: Allow
              - Action:
                  - sns:CreateTopic
                  - sns:DeleteTopic
                  - sns:GetTopicAttributes
                  - sns:SetTopicAttributes
                  - sns:TagResource
                  - sns:UntagResource
                Effect: "Allow"
                Resource: "*"
              - Action:
                  - codebuild:CreateReportGroup
                  - codebuild:CreateReport
                  - codebuild:UpdateReport
                  - codebuild:BatchPutTestCases
                  - codebuild:BatchPutCodeCoverages
                Effect: "Allow"
                Resource: "*"
              - Action:
                  - ecr:BatchCheckLayerAvailability
                  - ecr:BatchGetImage
                  - ecr:CompleteLayerUpload
                  - ecr:GetAuthorizationToken
                  - ecr:GetDownloadUrlForLayer
                  - ecr:InitiateLayerUpload
                  - ecr:PutImage
                  - ecr:UploadLayerPart
                  - ecr:DescribeRepositories
                  - ecr:CreateRepository
                  - ecr:SetRepositoryPolicy
                  - ecr:GetRepositoryPolicy
                Effect: Allow
                Resource: "*"
              - Action:
                  - cloudfront:UpdateDistribution
                Effect: Allow
                Resource: "*"
              - Action:
                  - kinesis:CreateStream
                  - kinesis:DeleteStream
                  - kinesis:DescribeStream
                  - kinesis:DescribeStreamSummary
                  - kinesis:AddTagsToStream
                  - kinesis:UpdateStreamMode
                Effect: "Allow"
                Resource: "*"
              - Action:
                  - states:CreateStateMachine
                  - states:UpdateStateMachine
                  - states:DeleteStateMachine
                  - states:TagResource
                  - states:DescribeStateMachine
                Effect: "Allow"
                Resource: "*"
              - Action:
                  - sqs:CreateQueue
                  - sqs:DeleteQueue
                  - sqs:GetQueueAttributes
                  - sqs:TagQueue
                  - sqs:UntagQueue
                  - sqs:ListQueueTags
                  - sqs:SetQueueAttributes
                Effect: "Allow"
                Resource: "*"
              - Action:
                  - ses:*
                Effect: "Allow"
                Resource: "*"