AWSTemplateFormatVersion: "2010-09-09"

Description: CodeBuild Stack

Metadata:
# ------------------------------------------------------------#
# Metadata
# ------------------------------------------------------------# 
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label: 
          default: Parameters for CodeCommit
        Parameters:
          - Description
          - Name

Parameters:
# ------------------------------------------------------------#
# Parameters
# ------------------------------------------------------------# 
  Description:
    MaxLength: 255
    Type: String

  Name:
    MaxLength: 255
    Type: String

  BuildSpec:
    MaxLength: 255
    Type: String

  CodeBuildRole:
    Type: String
    Description: "CodeBuild Role ARN"

Resources:
# ------------------------------------------------------------#
# CodeBuild
# ------------------------------------------------------------# 
  CodeBuild:
    Type: AWS::CodeBuild::Project
    Properties: 
      Artifacts:
        Type: CODEPIPELINE
      Description: !Ref Description
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        Type: LINUX_CONTAINER
      Name: !Ref Name
      ServiceRole: !Ref CodeBuildRole
      Source: 
        BuildSpec: !Ref BuildSpec
        Type: CODEPIPELINE

Outputs:
# ------------------------------------------------------------#
# Outputs
# ------------------------------------------------------------# 
  CodeBuildProjectname:
    Value: !Ref CodeBuild
    Export: 
      Name: codebuild-project-name

  CodeBuildProjectARN:
    Value: !GetAtt CodeBuild.Arn
    Export: 
      Name: codebuild-project-arn